### ISSUE TITLE
PollEvent() fails outside package main on macOS Sierra

### ISSUE THREAD

**Issue by ZeroXLR** [veandco/go-sdl2#246]
**Operating system**: macOS Sierra 10.12.6

I ran `go test -v` in the **go-sdl2/sdl** directory and an uncaught exception was thrown. The culprit is the `PollEvent()` call in **go-sdl2/sdl/events_test.go**. Here is a minimal example that replicates the failure (run `go test foo_test.go` on this):

```go
package foo
// package main

import (
	"testing"
	"github.com/veandco/go-sdl2/sdl"
)

func TestFoo(t *testing.T) {
	sdl.Init(sdl.INIT_EVERYTHING)
	defer sdl.Quit()

	sdl.PollEvent() // BAD!!
}

// func main()  {
// 	sdl.Init(sdl.INIT_EVERYTHING)
// 	defer sdl.Quit()
//
// 	sdl.PollEvent()
// }
```

and here is the stack trace of the failure:

```
2017-09-07 12:31:52.809 foo.test[8900:29022] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffd466a2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffe947a48d objc_exception_throw + 48
	2   AppKit                              0x00007fffd2855e82 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4480
	3   libSDL2-2.0.0.dylib                 0x00000000042f0c9b Cocoa_PumpEvents + 247
	4   libSDL2-2.0.0.dylib                 0x0000000004290568 SDL_PumpEvents_REAL + 23
	5   libSDL2-2.0.0.dylib                 0x00000000042905d0 SDL_WaitEventTimeout_REAL + 57
	6   foo.test                            0x00000000040f59fd _cgo_f7c1af2e6e77_Cfunc_SDL_PollEvent + 29
	7   foo.test                            0x0000000004058530 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fffe9e8ed42 m=5 sigcode=0
signal arrived during cgo execution

goroutine 19 [syscall, locked to thread]:
runtime.cgocall(0x40f59e0, 0xc420028f18, 0x42118e0)
	/usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc420028ee8 sp=0xc420028ea8 pc=0x4004b24
github.com/veandco/go-sdl2/sdl._Cfunc_SDL_PollEvent(0x42118e0, 0x0)
	github.com/veandco/go-sdl2/sdl/_obj/_cgo_gotypes.go:5552 +0x49 fp=0xc420028f18 sp=0xc420028ee8 pc=0x40f2959
github.com/veandco/go-sdl2/sdl.PollEvent.func1(0x42118e0, 0xc420028f88)
	/Users/Veritas/Desktop/go/src/github.com/veandco/go-sdl2/sdl/events.go:468 +0xa4 fp=0xc420028f58 sp=0xc420028f18 pc=0x40f3604
github.com/veandco/go-sdl2/sdl.PollEvent(0x0, 0x414c938)
	/Users/Veritas/Desktop/go/src/github.com/veandco/go-sdl2/sdl/events.go:468 +0x2d fp=0xc420028f80 sp=0xc420028f58 pc=0x40f2d2d
command-line-arguments.TestFoo(0xc4200aa0f0)
	/Users/Veritas/Desktop/foo_test.go:13 +0x4a fp=0xc420028fa8 sp=0xc420028f80 pc=0x40f4a4a
testing.tRunner(0xc4200aa0f0, 0x414c880)
	/usr/local/go/src/testing/testing.go:746 +0xd0 fp=0xc420028fd0 sp=0xc420028fa8 pc=0x40b7a60
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420028fd8 sp=0xc420028fd0 pc=0x40598c1
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 1 [chan receive, locked to thread]:
testing.(*T).Run(0xc4200aa000, 0x41447ae, 0x7, 0x414c880, 0x406be46)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200aa000)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200aa000, 0xc42004fde0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc420094020, 0x41ed670, 0x1, 0x1, 0x4012a87)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42004ff18, 0xc42004ff70)
	/usr/local/go/src/testing/testing.go:921 +0x111
main.main()
	command-line-arguments/_test/_testmain.go:44 +0xdb

rax    0x0
rbx    0x6
rcx    0x700000d85488
rdx    0x0
rdi    0x1003
rsi    0x6
rbp    0x700000d854b0
rsp    0x700000d85488
r8     0x7fffe9e1d650
r9     0x7fffe9ddfa50
r10    0x8000000
r11    0x206
r12    0x700000d85610
r13    0x30
r14    0x700000d87000
r15    0x8
rip    0x7fffe9e8ed42
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
FAIL	command-line-arguments	0.355s
```

When I uncomment the blocked out code in **foo_test.go** and run the file as main, the problem disappears. It appears that I cannot call `PollEvent()` outside the main thread.

**Comment by veeableful** [comment]
Hi @ZeroXLR,

It doesn't seem to happen on Linux. I'll try later on my Macbook Air =)

**Comment by ZeroXLR** [comment]
@veeableful Indeed, it appears to be an Apple-exclusive problem: the exception thrown is an Objective C exception after all.

**Comment by veeableful** [comment]
Weird, it seems removing `runtime.LockOSThread()` from the library fixes it. I'll look into this more.

**Comment by ZeroXLR** [comment]
@veeableful Can you tell me what you did? I'd like to try out that fix on my fork too

**Comment by veeableful** [comment]
I removed `runtime.LockOSThread()` from the `init()` in `sdl.go`. Then removed the `runtime` import in the same file. I'm not sure if that counts as fix though :P

**Comment by ZeroXLR** [comment]
Hmm. I will try that out. By the way, here is an even shorter example that causes the failure:

```go
package main

import (
	"runtime"
	"github.com/veandco/go-sdl2/sdl"
)

func main() {
	done := make(chan bool, 1)

	sdl.Init(sdl.INIT_EVERYTHING)
	defer sdl.Quit()

	go func() {
		sdl.PollEvent()
		done <- true
	}()

	<- done
}
```

Basically, `PollEvent()` crashes whenever it is in _some_ thread different from main. I don't know whether that helps you understand what is going on.

**Comment by ZeroXLR** [comment]
An obvious but adhoc solution is possible by doing an `unlockOSThread()` inside `TestMain(m *testing.M)` before the other tests begin. I will submit a pull request with the patch. However, reading through related issues like [**golang/go/issues/7905**](https://github.com/golang/go/issues/7905) make me think that there should be a more
 comprehensive way to resolve this...

**Comment by veeableful** [comment]
I agree. I've merged the pull request for now and hopefully will find solution to this.

**Comment by ZeroXLR** [comment]
I have confirmed that the tests still fail by running `go test -v -race`. However, it only fails sometimes now. Depending on how you look at it, this may be worse as it is a hidden bug.

**Comment by veeableful** [comment]
It is known that [SDL_PollEvent](https://wiki.libsdl.org/SDL_PollEvent) should be run in the main thread according to [SDL_PumpEvents](https://wiki.libsdl.org/SDL_PumpEvents). Perhaps we just need to find a way to do that in the test.

**Comment by ZeroXLR** [comment]
There is certainly a way of doing that by wrapping each `PollEvent()`/`WaitEvent()` calls that I could find with `sdl.Do(..)`s and calling `sdl.Main(..)` from `TestMain(..)`. This was the way I was originally trying to solve the problem. But I always end up getting a message: `2017-09-12 10:41:14.346 sdl.test[8522:53069] !!! BUG: The current event queue and the main event queue are not the same. Events will not be handled correctly. This is probably because _TSGetMainThread was called for the first time off the main thread.`.

This message DOES NOT break the tests though (which continue after that message) as far as I know. So if there are not better solutions, we could go with that...

**Comment by ZeroXLR** [comment]
With this issue seemingly fixed by 4fc54e5 I will close it.
